services:
  - type: web
    name: schoolapp
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    healthCheckPath: /Account/Login
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        sync: false
